# 1. 기본적인 DNN

# 2. 사이킷런(sklearn)이용
- 원핫인코딩을 하지 않고 라벨인코딩까지만 해야 작동. 원핫인코딩은 작동하지 않음

In [1]:
from sklearn import datasets # iris 데이터
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [7]:
# 1. 데이터
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print(iris_X[::50], iris_y[::50])
train_X, test_X, train_y, test_y = train_test_split(iris_X, iris_y,
                                                    test_size=0.1, # 기본값은 train:test = 0.75:0.25
                                                    random_state=4,
                                                    stratify=iris_y)
print(train_X.shape, test_X.shape, train_y.shape, test_y.shape)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]] [0 1 2]
(135, 4) (15, 4) (135,) (15,)


In [17]:
# 사이킷런에서 제공하는 다층퍼셉트론 기반의 분류 알고리즘 api
mlp = MLPClassifier(hidden_layer_sizes=(80,50,30),
                    activation='relu',
                    solver='adam', # adam이 기본값, optimizer
                    max_iter=1000, # 최대학습횟수
                    early_stopping=True, # 조기종료 활성화
                    n_iter_no_change=10, # 검증셋 손실함수가 개선되지 않으면 조기종료, 기본값 10
                    validation_fraction=0.1) # 검증셋 비율, 기본값 0.1

In [18]:
mlp.fit(train_X, train_y)

MLPClassifier(early_stopping=True, hidden_layer_sizes=(80, 50, 30),
              max_iter=1000)

In [22]:
mlp.score(test_X, test_y)

1.0

In [23]:
test_X[0], test_y[0]

(array([5.1, 3.8, 1.6, 0.2]), 0)

In [25]:
mlp.predict(test_X[0:1])

array([0])

# 3. 클래스를 생성

In [26]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

In [32]:
class DNNClassifier:
    @staticmethod
    def build(input_dim=4, activation='relu', output_dim=3):
#         model = Sequential()
#         model.add(Input(input_dim))
#         model.add(Dense(50, activation=activation))
#         model.add(Dense(30, activation=activation))
#         model.add(Dense(output_dim, activation='softmax'))
        model = Sequential([
            Input(input_dim),
            Dense(50, activation=activation),
            Dense(30, activation=activation),
            Dense(output_dim, activation='softmax')
        ])
        # 학습 과정 설정
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model

In [37]:
# 1. 데이터 생성 및 전처리
# iris_Y = pd.get_dummies(iris_y).values
# train_X, test_X, train_Y, test_Y = train_test_split(iris_X, iris_Y, # 원핫인코딩한 데이터로 분류
#                                                     test_size=0.1, # 기본값은 train:test = 0.75:0.25
#                                                     random_state=4,
#                                                     stratify=iris_y)
# print(train_X.shape, test_X.shape, train_Y.shape, test_Y.shape)
train_Y = pd.get_dummies(train_y).values
test_Y = pd.get_dummies(test_y).values
# 2. 모델
model = DNNClassifier.build(input_dim=4, activation='relu', output_dim=3)
# 3. 모델학습
earlystopping = EarlyStopping(patience = 150)
hist = model.fit(train_X, train_Y, epochs=1000, validation_split=0.1, callbacks=[earlystopping])

Epoch 1/1000
4/4 [==============================] - 0s 55ms/step - loss: 1.1151 - accuracy: 0.3471 - val_loss: 1.0462 - val_accuracy: 0.2143
Epoch 2/1000
4/4 [==============================] - 0s 14ms/step - loss: 1.0039 - accuracy: 0.4793 - val_loss: 1.0011 - val_accuracy: 0.2143
Epoch 3/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.9536 - accuracy: 0.5041 - val_loss: 0.9895 - val_accuracy: 0.5714
Epoch 4/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.9222 - accuracy: 0.5785 - val_loss: 0.9645 - val_accuracy: 0.7857
Epoch 5/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.8927 - accuracy: 0.6446 - val_loss: 0.9271 - val_accuracy: 0.7857
Epoch 6/1000
4/4 [==============================] - 0s 15ms/step - loss: 0.8613 - accuracy: 0.6529 - val_loss: 0.8680 - val_accuracy: 0.7857
Epoch 7/1000
4/4 [==============================] - 0s 15ms/step - loss: 0.8281 - accuracy: 0.6529 - val_loss: 0.8037 - val_accuracy: 0.7857
Epoch 8/1000


Epoch 59/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1512 - accuracy: 0.9917 - val_loss: 0.1650 - val_accuracy: 0.9286
Epoch 60/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1465 - accuracy: 0.9835 - val_loss: 0.1681 - val_accuracy: 0.9286
Epoch 61/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.1426 - accuracy: 0.9835 - val_loss: 0.1655 - val_accuracy: 0.9286
Epoch 62/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1389 - accuracy: 0.9835 - val_loss: 0.1609 - val_accuracy: 0.9286
Epoch 63/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1361 - accuracy: 0.9835 - val_loss: 0.1601 - val_accuracy: 0.9286
Epoch 64/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1336 - accuracy: 0.9835 - val_loss: 0.1617 - val_accuracy: 0.9286
Epoch 65/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1307 - accuracy: 0.9835 - val_loss: 0.1598 - val_accuracy: 0.9286
Epoch 

4/4 [==============================] - 0s 12ms/step - loss: 0.0751 - accuracy: 0.9835 - val_loss: 0.1434 - val_accuracy: 0.9286
Epoch 117/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0721 - accuracy: 0.9917 - val_loss: 0.1343 - val_accuracy: 0.9286
Epoch 118/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0711 - accuracy: 0.9917 - val_loss: 0.1310 - val_accuracy: 0.8571
Epoch 119/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0712 - accuracy: 0.9917 - val_loss: 0.1321 - val_accuracy: 0.9286
Epoch 120/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0711 - accuracy: 0.9917 - val_loss: 0.1386 - val_accuracy: 0.9286
Epoch 121/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0709 - accuracy: 0.9917 - val_loss: 0.1395 - val_accuracy: 0.9286
Epoch 122/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0712 - accuracy: 0.9917 - val_loss: 0.1321 - val_accuracy: 0.9286
Epoch 123/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0582 - accuracy: 0.9917 - val_loss: 0.1335 - val_accuracy: 0.8571
Epoch 174/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0599 - accuracy: 0.9917 - val_loss: 0.1326 - val_accuracy: 0.8571
Epoch 175/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0584 - accuracy: 0.9917 - val_loss: 0.1410 - val_accuracy: 0.9286
Epoch 176/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0574 - accuracy: 0.9917 - val_loss: 0.1392 - val_accuracy: 0.9286
Epoch 177/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0579 - accuracy: 0.9917 - val_loss: 0.1377 - val_accuracy: 0.9286
Epoch 178/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0565 - accuracy: 0.9917 - val_loss: 0.1319 - val_accuracy: 0.8571
Epoch 179/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0577 - accuracy: 0.9917 - val_loss: 0.1324 - val_accuracy: 0.8571
Epoch 180/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0520 - accuracy: 0.9917 - val_loss: 0.1407 - val_accuracy: 0.9286
Epoch 231/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0516 - accuracy: 0.9917 - val_loss: 0.1397 - val_accuracy: 0.8571
Epoch 232/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0525 - accuracy: 0.9917 - val_loss: 0.1389 - val_accuracy: 0.8571
Epoch 233/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0512 - accuracy: 0.9917 - val_loss: 0.1420 - val_accuracy: 0.9286
Epoch 234/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0530 - accuracy: 0.9917 - val_loss: 0.1396 - val_accuracy: 0.8571
Epoch 235/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0515 - accuracy: 0.9917 - val_loss: 0.1414 - val_accuracy: 0.9286
Epoch 236/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.0510 - accuracy: 0.9917 - val_loss: 0.1435 - val_accuracy: 0.9286
Epoch 237/1000

In [38]:
loss, accuracy = model.evaluate(test_X, test_Y)
print('정확도 : {}% loss : {}'.format(accuracy*100, loss))

1/1 [==============================] - 0s 30ms/step - loss: 0.0435 - accuracy: 1.0000
정확도 : 100.0% loss : 0.04345144331455231


In [39]:
model.predict(test_X[0].reshape(1,-1)).argmax(axis=1)

1/1 [==============================] - 0s 81ms/step


array([0], dtype=int64)

# 4. 병렬처리

In [42]:
from tensorflow.keras.layers import concatenate
from tensorflow.keras import Model

In [41]:
test_X.shape, test_Y.shape, train_X.shape, train_Y.shape

((15, 4), (15, 3), (135, 4), (135, 3))

In [43]:
# 모델 구성
input_ = Input(shape=(4,))
dense1 = Dense(50, activation='relu')(input_)
dense2 = Dense(80, activation='relu')(input_)
dense3 = Dense(30, activation='relu')(input_)
x = concatenate([dense1, dense2, dense3])
# x = Dense(units=160, activation='relu')(input_)의 병렬처리 구현
output = Dense(units=3, activation='softmax')(x)
model = Model(inputs=input_, outputs=output)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 4)]          0           []                               
                                                                                                  
 dense_12 (Dense)               (None, 50)           250         ['input_5[0][0]']                
                                                                                                  
 dense_13 (Dense)               (None, 80)           400         ['input_5[0][0]']                
                                                                                                  
 dense_14 (Dense)               (None, 30)           150         ['input_5[0][0]']                
                                                                                              

In [44]:
# 학습 정의(정의), 학습
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_X, train_Y, epochs=1000, verbose=1)

Epoch 1/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.1863 - accuracy: 0.4444
Epoch 2/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.8590 - accuracy: 0.6667
Epoch 3/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.7674 - accuracy: 0.7185
Epoch 4/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.7273 - accuracy: 0.7037
Epoch 5/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.6698 - accuracy: 0.7407
Epoch 6/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.6245 - accuracy: 0.6741
Epoch 7/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.5924 - accuracy: 0.7333
Epoch 8/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.5672 - accuracy: 0.9037
Epoch 9/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.5402 - accuracy: 0.9481
Epoch 10/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.5212 - accuracy: 0.8000
Epoch 11/1000
5/5 [

5/5 [==============================] - 0s 5ms/step - loss: 0.1455 - accuracy: 0.9778
Epoch 84/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.1473 - accuracy: 0.9778
Epoch 85/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1432 - accuracy: 0.9778
Epoch 86/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1398 - accuracy: 0.9778
Epoch 87/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1474 - accuracy: 0.9704
Epoch 88/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1405 - accuracy: 0.9630
Epoch 89/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1365 - accuracy: 0.9778
Epoch 90/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1354 - accuracy: 0.9778
Epoch 91/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.1339 - accuracy: 0.9778
Epoch 92/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.1324 - accuracy: 0.9778
Epoch 93/1000
5/5 [=====

5/5 [==============================] - 0s 4ms/step - loss: 0.0884 - accuracy: 0.9778
Epoch 166/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0854 - accuracy: 0.9852
Epoch 167/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0854 - accuracy: 0.9852
Epoch 168/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0850 - accuracy: 0.9778
Epoch 169/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0857 - accuracy: 0.9778
Epoch 170/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0830 - accuracy: 0.9852
Epoch 171/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0918 - accuracy: 0.9704
Epoch 172/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0835 - accuracy: 0.9852
Epoch 173/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0847 - accuracy: 0.9778
Epoch 174/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0869 - accuracy: 0.9778
Epoch 175/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0696 - accuracy: 0.9778
Epoch 248/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0675 - accuracy: 0.9852
Epoch 249/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0681 - accuracy: 0.9778
Epoch 250/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0702 - accuracy: 0.9778
Epoch 251/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0688 - accuracy: 0.9778
Epoch 252/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0678 - accuracy: 0.9852
Epoch 253/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0690 - accuracy: 0.9778
Epoch 254/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0814 - accuracy: 0.9630
Epoch 255/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0789 - accuracy: 0.9778
Epoch 256/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0670 - accuracy: 0.9778
Epoch 257/1000


5/5 [==============================] - 0s 8ms/step - loss: 0.0627 - accuracy: 0.9778
Epoch 330/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0639 - accuracy: 0.9778
Epoch 331/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0612 - accuracy: 0.9778
Epoch 332/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0661 - accuracy: 0.9852
Epoch 333/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0600 - accuracy: 0.9852
Epoch 334/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0729 - accuracy: 0.9778
Epoch 335/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0638 - accuracy: 0.9778
Epoch 336/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0630 - accuracy: 0.9852
Epoch 337/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0637 - accuracy: 0.9852
Epoch 338/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0597 - accuracy: 0.9852
Epoch 339/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0564 - accuracy: 0.9778
Epoch 412/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0563 - accuracy: 0.9852
Epoch 413/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0570 - accuracy: 0.9852
Epoch 414/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0572 - accuracy: 0.9852
Epoch 415/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0565 - accuracy: 0.9852
Epoch 416/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0565 - accuracy: 0.9852
Epoch 417/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0560 - accuracy: 0.9852
Epoch 418/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0590 - accuracy: 0.9852
Epoch 419/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0562 - accuracy: 0.9852
Epoch 420/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0577 - accuracy: 0.9778
Epoch 421/1000


5/5 [==============================] - 0s 7ms/step - loss: 0.0544 - accuracy: 0.9852
Epoch 494/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0579 - accuracy: 0.9778
Epoch 495/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0549 - accuracy: 0.9852
Epoch 496/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0549 - accuracy: 0.9852
Epoch 497/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0532 - accuracy: 0.9852
Epoch 498/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0548 - accuracy: 0.9778
Epoch 499/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0541 - accuracy: 0.9852
Epoch 500/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0558 - accuracy: 0.9852
Epoch 501/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0530 - accuracy: 0.9852
Epoch 502/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0547 - accuracy: 0.9852
Epoch 503/1000


5/5 [==============================] - 0s 5ms/step - loss: 0.0566 - accuracy: 0.9852
Epoch 576/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0568 - accuracy: 0.9852
Epoch 577/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0541 - accuracy: 0.9852
Epoch 578/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0579 - accuracy: 0.9852
Epoch 579/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0518 - accuracy: 0.9852
Epoch 580/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0511 - accuracy: 0.9852
Epoch 581/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0526 - accuracy: 0.9852
Epoch 582/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0522 - accuracy: 0.9852
Epoch 583/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0503 - accuracy: 0.9926
Epoch 584/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0527 - accuracy: 0.9852
Epoch 585/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0494 - accuracy: 0.9852
Epoch 658/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0497 - accuracy: 0.9852
Epoch 659/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0511 - accuracy: 0.9852
Epoch 660/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0495 - accuracy: 0.9852
Epoch 661/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0529 - accuracy: 0.9852
Epoch 662/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0540 - accuracy: 0.9852
Epoch 663/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0506 - accuracy: 0.9852
Epoch 664/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0488 - accuracy: 0.9926
Epoch 665/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0526 - accuracy: 0.9852
Epoch 666/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0486 - accuracy: 0.9852
Epoch 667/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0494 - accuracy: 0.9852
Epoch 740/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0545 - accuracy: 0.9852
Epoch 741/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0484 - accuracy: 0.9778
Epoch 742/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0564 - accuracy: 0.9778
Epoch 743/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0500 - accuracy: 0.9852
Epoch 744/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0525 - accuracy: 0.9852
Epoch 745/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0506 - accuracy: 0.9852
Epoch 746/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0509 - accuracy: 0.9852
Epoch 747/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0482 - accuracy: 0.9926
Epoch 748/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0511 - accuracy: 0.9852
Epoch 749/1000


5/5 [==============================] - 0s 5ms/step - loss: 0.0680 - accuracy: 0.9630
Epoch 822/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0409 - accuracy: 0.9852
Epoch 823/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0732 - accuracy: 0.9704
Epoch 824/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0457 - accuracy: 0.9778
Epoch 825/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.1363 - accuracy: 0.9407
Epoch 826/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0782 - accuracy: 0.9778
Epoch 827/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0509 - accuracy: 0.9778
Epoch 828/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0627 - accuracy: 0.9778
Epoch 829/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0526 - accuracy: 0.9852
Epoch 830/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0536 - accuracy: 0.9852
Epoch 831/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0482 - accuracy: 0.9852
Epoch 904/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0487 - accuracy: 0.9852
Epoch 905/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0498 - accuracy: 0.9852
Epoch 906/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0503 - accuracy: 0.9852
Epoch 907/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0499 - accuracy: 0.9852
Epoch 908/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0504 - accuracy: 0.9852
Epoch 909/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0472 - accuracy: 0.9852
Epoch 910/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0484 - accuracy: 0.9852
Epoch 911/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0453 - accuracy: 0.9852
Epoch 912/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0492 - accuracy: 0.9852
Epoch 913/1000


5/5 [==============================] - 0s 4ms/step - loss: 0.0461 - accuracy: 0.9926
Epoch 986/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0453 - accuracy: 0.9852
Epoch 987/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0455 - accuracy: 0.9852
Epoch 988/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0471 - accuracy: 0.9852
Epoch 989/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0452 - accuracy: 0.9852
Epoch 990/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0468 - accuracy: 0.9926
Epoch 991/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0460 - accuracy: 0.9852
Epoch 992/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0505 - accuracy: 0.9778
Epoch 993/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.0562 - accuracy: 0.9704
Epoch 994/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0508 - accuracy: 0.9778
Epoch 995/1000


In [45]:
# 학습평가
loss, accuracy = model.evaluate(test_X, test_Y)
print(accuracy*100,'%')

1/1 [==============================] - 0s 156ms/step - loss: 0.0810 - accuracy: 0.9333
93.33333373069763 %
