<b><font color="red" size="6">ch12. 데이터프레임과 시리즈(Pandas)</font></b>
- pip install pandas

# 1절. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈, 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 
              데이터 프레임 생성, 파일io, 레이블링, 부분데이터추출, 크기변경(행이나 열삽입, 삭제)
              데이터 분할, 병합, 데이터 정렬, 결측치 처리, 피벗과 언피벗등에 용이
- https://pypi.org/project/pandas/ (package index)
- https://pandas.pydata.org/docs/reference/index.html#api (API reference)

In [1]:
import pandas as pd
pd.__version__

'1.5.3'

In [2]:
data = pd.read_json('data/ch09_member1.json', encoding='cp949') # encoding 기본값 : utf-8
display(data)
print(type(data))

name  age    email address
0  홍길동   20  h@h.com      서울
1  김길동   20  k@h.com      부산
2  신길동   20  s@h.com      안양

<class 'pandas.core.frame.DataFrame'>


In [3]:
member4 = pd.read_csv('data/ch09_member4.csv')
member4.head() # 최초 상위 5개행 가져오기

Name  Age             Email   Address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구
3  홍길동   20  kildong@hong.com   서울시 관악구
4  김길동   40  kimdong@hong.com  서울시 영등포구

In [4]:
member1 = pd.read_csv('data/ch09_member1.csv', header=None, names=['Name', 'Age', 'Email','Address'])
member1

Name  Age             Email   Address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   20  kimdong@hong.com  서울시 영등포구
2  신길동   20  sindong@hong.com   서울시 동작구

In [5]:
iris = pd.read_hdf('data/ch09_iris2.hdf5', key='iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2절. 데이터 프레임 만들
## 2.1 딕셔너리를 이용해서 데이터프레임 만들기

In [6]:
# value가 list인 딕셔너리를 데이터프레임으로
d = {'kor':[100,90], 'mat':[95,99]}
df = pd.DataFrame(data = d)
df

kor  mat
0  100   95
1   90   99

In [7]:
d = [{'kor':100, 'mat':99}]
pd.DataFrame(d)

kor  mat
0  100   99

In [8]:
df.to_dict() # 데이터 프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [9]:
df.to_numpy() # 데이터프레임을 넘파이배열

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [10]:
# 딕셔너리 리스트를 데이터프레임으로
d = [{'kor':100, 'mat':95}, {'kor':90, 'mat':99}]
df = pd.DataFrame(data = d)
df

kor  mat
0  100   95
1   90   99

In [11]:
df.dtypes

kor    int64
mat    int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [13]:
df.dtypes.to_dict()

{'kor': dtype('int64'), 'mat': dtype('int64')}

In [14]:
df['kor'].dtype

dtype('int64')

In [15]:
import numpy as np
df['kor'] = df['kor'].astype(np.float64)

In [16]:
d = [{'kor':100, 'mat':100}, {'kor':90, 'mat':99}, {'kor':83, 'eng':85}]
df = pd.DataFrame(d)
df

kor    mat   eng
0  100  100.0   NaN
1   90   99.0   NaN
2   83    NaN  85.0

In [17]:
type(np.nan)

float

In [18]:
# 결측치는 int로 형변환 불가(결측치를 대체값으로 치완 후 변환) df['mat'].astype(np.int32)

## 2.2 리스트를 이용해서 데이터 프레임 만들기

In [19]:
kor = [100,90,95,90,65]
eng = [100,95,94,64,85]
df = pd.DataFrame({'kor':kor, 'eng':eng})
df

kor  eng
0  100  100
1   90   95
2   95   94
3   90   64
4   65   85

In [20]:
np.c_[kor, eng]

array([[100, 100],
       [ 90,  95],
       [ 95,  94],
       [ 90,  64],
       [ 65,  85]])

In [21]:
df = pd.DataFrame(np.c_[kor, eng], columns = ['Kor','Eng'])
df

Kor  Eng
0  100  100
1   90   95
2   95   94
3   90   64
4   65   85

In [22]:
l = [[100,90],[10,20]]
df = pd.DataFrame(l, columns=['kor', 'eng'])
df

kor  eng
0  100   90
1   10   20

In [89]:
%ls D:\KHH\ai\Download\shareData\상가정보

 D 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: C65B-EB1E

 D:\KHH\ai\Download\shareData\상가정보 디렉터리

2024-11-25  오후 07:13    <DIR>          .
2024-11-25  오후 07:13    <DIR>          ..
2024-10-23  오후 05:58             1,011 [필독]파일열람방법.txt
2024-10-23  오후 06:19        53,454,658 소상공인시장진흥공단_상가(상권)정보_강원_202409.csv
2024-10-23  오후 06:19       301,935,950 소상공인시장진흥공단_상가(상권)정보_경기_202409.csv
2024-10-23  오후 06:20        86,291,699 소상공인시장진흥공단_상가(상권)정보_경남_202409.csv
2024-10-23  오후 06:20        70,952,897 소상공인시장진흥공단_상가(상권)정보_경북_202409.csv
2024-10-23  오후 06:20        36,458,714 소상공인시장진흥공단_상가(상권)정보_광주_202409.csv
2024-10-23  오후 06:20        57,391,847 소상공인시장진흥공단_상가(상권)정보_대구_202409.csv
2024-10-23  오후 06:20        36,638,904 소상공인시장진흥공단_상가(상권)정보_대전_202409.csv
2024-10-23  오후 06:20        78,253,942 소상공인시장진흥공단_상가(상권)정보_부산_202409.csv
2024-10-23  오후 06:18       254,255,270 소상공인시장진흥공단_상가(상권)정보_서울_202409.csv
2024-10-23  오후 06:18         8,277,492 소상공인시장진흥공단_상가(상권)정보_세종_202409.csv
2024-10-23  오후 06:18        26,299,042 소상공인시장진

In [90]:
df = pd.read_csv(r'D:\KHH\ai\Download\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_세종_202409.csv', encoding='utf-8', sep=',', low_memory=False,nrows=30) # 기본값은 생략가능
df.shape

(30, 39)

In [91]:
df

상가업소번호              상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드  \
0   MA0101202210A0084499         베트남쌀국수퍼짱  NaN        I2       음식      I205   
1   MA010120220805434190        더함인테리어컨설팅  NaN        M1    과학·기술      M112   
2   MA010120220805432469           모더니엘살롱  NaN        S2    수리·개인      S207   
3   MA010120220805435562            카이젠교육  NaN        P1       교육      P105   
4   MA010120220805437826             가재세탁  NaN        S2    수리·개인      S209   
5   MA010120220805437034            세종마취과  NaN        Q1     보건의료      Q102   
6   MA010120220805436870            세종유도관  NaN        P1       교육      P106   
7   MA010120220805439448        세종종합법률사무소  NaN        M1    과학·기술      M103   
8   MA010120220805447501              로엘라  NaN        I2       음식      I201   
9   MA010120220805445058              딥핑크  NaN        G2       소매      G204   
10  MA010120220805446670            다카렌터카  NaN        N1  시설관리·임대      N109   
11  MA010120220805452173             경진상사  NaN        S2    수리·개인      S206   
12  MA010120220805448766         미요가.필라테스  NaN        P1       교육      P106   
13  MA010120220805446877         세종드럼뮤직학원  NaN        P1       교육      P106   
14  MA010120220805448536            혜성주얼리  NaN        G2       소매      G217   
15  MA010120220805441159              목향재  NaN        I1       숙박      I101   
16  MA010120220805440735           아름다운기획  NaN        M1    과학·기술      M105   
17  MA010120220805444116          스튜디오에프피  NaN        M1    과학·기술      M112   
18  MA010120220805442955             올진스시  NaN        I2       음식      I203   
19  MA010120220805441629            엄마손김밥  NaN        I2       음식      I210   
20  MA010120220805444812  부동산땅집go공인중개사사무소  NaN        L1      부동산      L102   
21  MA010120220805443708         머슬케어필라테스  NaN        P1       교육      P106   
22  MA010120220805442296            천지연가든  NaN        I2       음식      I201   
23  MA010120220805440526         아르드뽀에스테틱  NaN        S2    수리·개인      S207   
24  MA010120220805443477              쿠헤어  NaN        S2    수리·개인      S207   
25  MA010120220805457023         세종하이엔드학원  NaN        P1       교육      P105   
26  MA010120220805461877            캐치업세종  NaN        G2       소매      G215   
27  MA010120220805457615        인성세무회계사무소  NaN        M1    과학·기술      M104   
28  MA010120220805459636             모던제이  NaN        G2       소매      G209   
29  MA010120220805452812         엘리시아헤어살롱  NaN        S2    수리·개인      S207   

       상권업종중분류명 상권업종소분류코드          상권업종소분류명 표준산업분류코드  ...  \
0         동남아시아    I20501           베트남식 전문   I56194  ...   
1        전문 디자인    M11201         인테리어 디자인업   M73201  ...   
2         이용·미용    S20701               미용실   S96112  ...   
3         일반 교육    P10501           입시·교과학원   P85501  ...   
4            세탁    S20901               세탁소   S96912  ...   
5            의원    Q10209             기타 의원   Q86201  ...   
6         기타 교육    P10601          태권도/무술학원   P85611  ...   
7         법무관련     M10301               변호사   M71101  ...   
8            한식    I20101            백반/한정식   I56111  ...   
9         종합 소매    G20499     그 외 기타 종합 소매업   G47190  ...   
10      운송장비 대여    N10901           자동차 대여업   N76110  ...   
11   기타 가정용품 수리    S20601         의류/이불 수선업   S95391  ...   
12        기타 교육    P10603        요가/필라테스 학원   P85612  ...   
13        기타 교육    P10609              음악학원   P85621  ...   
14    시계·귀금속 소매    G21701        시계/귀금속 소매업   G47830  ...   
15        일반 숙박    I10102             여관/모텔   I55102  ...   
16           광고    M10504        광고물 설계/제작업   M71393  ...   
17       전문 디자인    M11204  패션/섬유/기타 전문 디자인업   M73209  ...   
18           일식    I20301           일식 회/초밥   I56122  ...   
19        기타 간이    I21007          김밥/만두/분식   I56194  ...   
20      부동산 서비스    L10203        부동산 중개/대리업   L68221  ...   
21        기타 교육    P10603        요가/필라테스 학원   P85612  ...   
22           한식    I20101            백반/한정식   I56111  ...   
23        이용·미용    S20702            피부 관리실   S96113  ...   
24        이용·미용    S20701               미용실

In [92]:
df.T

0                              1   \
상가업소번호          MA0101202210A0084499           MA010120220805434190   
상호명                         베트남쌀국수퍼짱                      더함인테리어컨설팅   
지점명                              NaN                            NaN   
상권업종대분류코드                         I2                             M1   
상권업종대분류명                          음식                          과학·기술   
상권업종중분류코드                       I205                           M112   
상권업종중분류명                       동남아시아                         전문 디자인   
상권업종소분류코드                     I20501                         M11201   
상권업종소분류명                     베트남식 전문                      인테리어 디자인업   
표준산업분류코드                      I56194                         M73201   
표준산업분류명              김밥 및 기타 간이 음식점업                      인테리어 디자인업   
시도코드                              36                             36   
시도명                          세종특별자치시                        세종특별자치시   
시군구코드                          36110                          36110   
시군구명                         세종특별자치시                        세종특별자치시   
행정동코드                       36110518                       36110360   
행정동명                             나성동                            연서면   
법정동코드                     3611010700                     3611036033   
법정동명                             나성동                            연서면   
지번코드             3611010700107320000            3611036033106370003   
대지구분코드                             1                              1   
대지구분명                             대지                             대지   
지번본번지                            732                            637   
지번부번지                            NaN                            3.0   
지번주소         세종특별자치시 세종특별자치시 나성동 732  세종특별자치시 세종특별자치시 연서면 봉암리 637-3   
도로명코드                   361102000002                   361103258005   
도로명            세종특별자치시 세종특별자치시 한누리대로        세종특별자치시 세종특별자치시 연서면 당산로   
건물본번지                            311                            294   
건물부번지                            NaN                            NaN   
건물관리번호     3611010700103610086000001      3611036033106370003000001   
건물명                            모닝시티2                            NaN   
도로명주소      세종특별자치시 세종특별자치시 한누리대로 311    세종특별자치시 세종특별자치시 연서면 당산로 294   
구우편번호                       339003.0                       339813.0   
신우편번호                          30123                          30047   
동정보                              NaN                            NaN   
층정보                              1.0                            NaN   
호정보                              NaN                            NaN   
경도                         127.25584                     127.278712   
위도                         36.492065                      36.559184   

                                  2                          3   \
상가업소번호          MA010120220805432469       MA010120220805435562   
상호명                           모더니엘살롱                      카이젠교육   
지점명                              NaN                        NaN   
상권업종대분류코드                         S2                         P1   
상권업종대분류명                       수리·개인                         교육   
상권업종중분류코드                       S207                       P105   
상권업종중분류명                       이용·미용                      일반 교육   
상권업종소분류코드                     S20701                     P10501   
상권업종소분류명                         미용실                    입시·교과학원   
표준산업분류코드                      S96112                     P85501   
표준산업분류명                       두발 미용업                    일반 교과학원   
시도코드                              36                         36   
시도명                          세종특별자치시                    세종특별자치시   
시군구코드                          36110                      36110   
시군구명                         세종특별자치시                    세종특별자치시   
행정동코드                       36110518                   36110560   
행정동명                             나성동                  

In [93]:
df.head(1) # 상위 1행만 출력

상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명  \
0  MA0101202210A0084499  베트남쌀국수퍼짱  NaN        I2       음식      I205    동남아시아   

  상권업종소분류코드 상권업종소분류명 표준산업분류코드  ...                     건물관리번호    건물명  \
0    I20501  베트남식 전문   I56194  ...  3611010700103610086000001  모닝시티2   

                       도로명주소     구우편번호  신우편번호  동정보  층정보  호정보         경도  \
0  세종특별자치시 세종특별자치시 한누리대로 311  339003.0  30123  NaN  1.0  NaN  127.25584   

          위도  
0  36.492065  

[1 rows x 39 columns]

In [ ]:
# 판다스 디스플레이 옵션
pd.options.display.max_columns = 40
pd.options.display.max_rows = 40
df.head(1)

## 2.3 read_csv

In [25]:
# (1) CSV 파일 불러오기 (기본값)
member = pd.read_csv('data/ch12_member.csv', encoding='utf-8', sep=',')
member

Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2   홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3   홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중   23   mid@hong.com   부산시 중구  1999-01-30
5  #홍길뜽   24    non@not.com      없는구  2000-01-01

In [26]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [27]:
# 문자로 읽어들인 Birth를 datetime형으로
# 형변환은 astype()쓰지만 datetime형으로 변환할 때는 to_datetime()함수를 사용
member['Birth'] = pd.to_datetime(member['Birth'])
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int64         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 368.0+ bytes


In [28]:
import numpy as np
member['Age'] = member['Age'].astype(np.int16)
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int16         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int16(1), object(3)
memory usage: 332.0+ bytes


In [29]:
# (2) 특정 몇행만 읽어오기
member = pd.read_csv('data/ch12_membercp949.csv', encoding='cp949', skiprows=[1,6]) # 1,6번째 행 제외하고 읽어오기(시작이 1부터)
member

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [30]:
# (3) 상위 5행만 읽어오기
member_df = pd.read_csv('data/ch12_membersep.csv', sep='|', nrows=5) # 상위 5개행만 읽어오기
member_df

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [31]:
# (4) 주석제외, datetime형 필드 지정하여 읽어오기
member_df = pd.read_csv('data/ch12_membertap.csv', sep='\t', parse_dates=['Birth'] # datetime형으로 읽어올 컬럼 지정
                        , comment='#') # #이 있는행은 제외하고 읽어오기
member_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     5 non-null      object        
 1   Age      5 non-null      int64         
 2   Email    5 non-null      object        
 3   Address  5 non-null      object        
 4   Birth    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 328.0+ bytes


## iris 데이터 가져오기 방법1 : sklearn(머신러닝패키지)
## iris 데이터 가져오기 방법2 : statsmodels(R데이터 가져오기)
## iris 데이터 가져오기 방법3 : seaborn(시각화 패키지)
## 2.4 sklearn.dataset 모듈 데이터(iris)를 데이터 프레임으로 변환

In [32]:
from sklearn import datasets
# import sklearn.datasets as datasets
# sklearn 패키는 머신러닝을 공부하기위한, 학습 데이터셋들을 제공
# sklearn 패키지에서 제공되는 데이터셋들은 딕셔너리 형식으로 제공
iris = datasets.load_iris()
iris # 딕셔너리 형태

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [33]:
print(iris.DESCR) # iris 데이터 셋에 대한 설명

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [34]:
iris.data # 독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [35]:
iris.feature_names # 독립변수의 열이름
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
# 데이터프레임에서 열이름
[col[:-4].strip().replace(' ','_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [37]:
[col[:12].strip().replace(' ','_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [38]:
iris.target
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
iris.target_names
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [40]:
# 데이터 프레임의 가장 오르쪽열
iris.target_names[iris.target]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [41]:
# 독립변수
data = iris.data
print(data[:5])
# 종속변수
target = iris.target_names[iris.target].reshape(-1,1)
print(target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']


In [42]:
print('독립변수 차원 :', data.shape)
print('종속변수 차원 :', target.shape)

독립변수 차원 : (150, 4)
종속변수 차원 : (150, 1)


In [43]:
pd.DataFrame(np.hstack((data, target)), columns=[col[:12].strip().replace(' ','_') for col in iris.feature_names]+['spacies'])

sepal_length sepal_width petal_length petal_width    spacies
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [44]:
df = pd.DataFrame(np.hstack((data, target)), columns=iris.feature_names+['spacies'])
df

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
..                ...              ...               ...              ...   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

       spacies  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [45]:
df.spacies # df['spacies']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: spacies, Length: 150, dtype: object

In [46]:
df['sepal length (cm)']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: object

In [47]:
# 독립변수, 종속변수를 따로 데이터프레임으로 만들고 두 데이터 프레임을 연결
X = pd.DataFrame(iris.data, columns=iris.feature_names) # x : 독립변수 데이터 프레임
X.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2

In [48]:
X.columns = [col[:-4].strip().replace(' ', '-') for col in iris.feature_names]

In [49]:
X.head(1)

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2

In [50]:
# y : 종속변수 데이터 프레임
y = pd.DataFrame(iris.target_names[iris.target], columns=['species'])
y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [51]:
print(X.index) # index : 행 이름
print(y.index)

RangeIndex(start=0, stop=150, step=1)
RangeIndex(start=0, stop=150, step=1)


In [52]:
# 데이터 프레임 연결하기 (열로 연결)
iris_df = pd.concat([X,y], axis=1)
iris_df

sepal-length  sepal-width  petal-length  petal-width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [53]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## 2.5 statsmodels 패키지의 iris

In [54]:
# iris 데이터 가져오기 방법2 : R 데이터 가져오기
import statsmodels.api as sm
iris_data = sm.datasets.get_rdataset('iris',package='datasets', cache=True)
iris_data

<class 'statsmodels.datasets.utils.Dataset'>

In [55]:
iris = iris_data.data
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [56]:
iris.columns = [col.replace('.','') for col in iris.columns]
iris.head(1)

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa

## 2.6 seaborn 패키지의 iris

In [57]:
# iris 데이터 가져오기 방법3 : seaborn
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [58]:
# 데이터 프레임을 파일로 출력 4k
iris.to_csv('data/ch12_iris.csv', index=False)# 행이름 생략되서 파일 출력

In [59]:
# 1k
iris.to_csv('data/ch12_iris.csv.gz', index=False, compression='infer')

In [60]:
read_iris = pd.read_csv('data/ch12_iris.csv.gz', compression='infer')
read_iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

# 3절 이름(열, 행) 지정하기
## 3.1 열이름 지정하기

In [61]:
member = pd.read_csv('data/ch12_member.csv', comment='#')
member

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [62]:
member.columns

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')

In [63]:
member.columns = ['이름', '나이', '메일', '주소', '생년월일']
member

이름  나이             메일       주소        생년월일
0  홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구  1999-01-30

## 3.2 행이름 지정

In [64]:
member.index

RangeIndex(start=0, stop=5, step=1)

In [65]:
member.index = range(10,15)
member

이름  나이             메일       주소        생년월일
10  홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
11  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
12  홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
13  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
14  홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [66]:
member.index = ['동','서','남','북','중']
member

이름  나이             메일       주소        생년월일
동  홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
서  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
남  홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
북  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
중  홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [67]:
member['이름']['서']

'홍길서'

In [68]:
member.loc['서', '이름'] # loc : 행이름과 열이름으로 데이터 프레임의 부분 데이터 조회

'홍길서'

In [69]:
# 이름을 행 이름으로 (실행결과가 출력되서 나오면 return될 뿐, member는 안바뀜)
# member를 수정하려면 (1) 할당 (2) inplace 매개변수에 True (기본값은 False)
member1 = member.set_index('이름')
member1

나이             메일       주소        생년월일
이름                                         
홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
홍길서  30   seo@hong.com   서울시 중구  1999-12-01
홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [70]:
member.set_index('이름', inplace=True)
member

나이             메일       주소        생년월일
이름                                         
홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
홍길서  30   seo@hong.com   서울시 중구  1999-12-01
홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [71]:
member.index

Index(['홍길동', '홍길서', '홍길남', '홍길북', '홍길중'], dtype='object', name='이름')

In [72]:
# 인덱스를 컬럼에 편입시키기
member.reset_index(inplace=True)
member

이름  나이             메일       주소        생년월일
0  홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [73]:
member.index = [0,11,2,13,4]
member

이름  나이             메일       주소        생년월일
0   홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
11  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
2   홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
13  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [74]:
# 기존 index를 새로운 열에 편입시키지 않고 완전히 제거 후 숫자 index로 초기화
member.reset_index(drop=True, inplace=True)
member

이름  나이             메일       주소        생년월일
0  홍길동  20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구  1999-01-30

In [75]:
member = pd.read_csv('data/ch12_member.csv', comment='#', parse_dates=['Birth'])
member

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [76]:
member.head(1)

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [77]:
member.loc[0, 'Birth']

Timestamp('1999-01-01 00:00:00')

In [78]:
# 시리즈.dt : datetime열에서 날짜 및 시간에 관련된 정보를 추출하기 위해 사용
member['Birth'].dt.year

0    1999
1    1999
2    1999
3    1999
4    1999
Name: Birth, dtype: int64

In [79]:
member['Birth'].dt.month

0     1
1    12
2    11
3     5
4     1
Name: Birth, dtype: int64

In [80]:
member['Birth'].dt.weekday# 0 월, 1 화........ 6 일

0    4
1    2
2    0
3    5
4    5
Name: Birth, dtype: int64

## 3.3 레벨이름 지정하기

In [81]:
member

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [82]:
member.columns = [['기본정보','기본정보','기본정보','추가정보','추가정보'],
                  ['이름', '나이', '메일', '주소', '생년월일']]
member.columns.names = ['대분류', '소분류']
member

대분류 기본정보                        추가정보           
소분류   이름  나이             메일       주소       생년월일
0    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [83]:
member.index = [['좌우','좌우','상하','상하','상하'],
                ['동','서','남','북','중']]
member

대분류  기본정보                        추가정보           
소분류    이름  나이             메일       주소       생년월일
좌우 동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
   서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
상하 남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
   북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
   중  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [84]:
member.loc['좌우','기본정보']['나이']

동    20
서    30
Name: 나이, dtype: int64

In [85]:
member.loc['좌우','기본정보'].loc['동','나이']

20